### ISSUE TITLE
refusing to convert between file and link for /usr/local/bin/docker-compose

### ISSUE THREAD

**Issue by metairie** [andrewrothstein/ansible-docker-compose#2]
I had this error on this step

TASK [andrewrothstein.docker-compose : link /usr/local/bin/docker-compose] *****

fatal: [1.2.3.4]: FAILED! => {"changed": false, "failed": true, "gid": 0, "group": "root", "mode": "0755", "msg": "refusing to convert between file and link for /usr/local/bin/docker-compose", "owner": "root", "path": "/usr/local/bin/docker-compose", "secontext": "unconfined_u:object_r:bin_t:s0", "size": 8273264, "state": "file", "uid": 0}

        to retry, use: --limit @/home/xxx/playbooks/docker/docker.retry

**Comment by metairie** [comment]
after installation (step before) there is already a file docker-compose

**Comment by andrewrothstein** [comment]
the role assumes that it owns a link at /usr/local/bin/docker-compose. if you've installed something else at this path the role won't work. did you install docker-compose via some other method prior to trying the role?

**Comment by metairie** [comment]
I have 3 machines, 1 with docker-compose and 2 without... the result is the same for all .
So I removed the link task, in the role tasks/main.yml , that works.

Why ? Because after the "downloading docker-compose" , I have two files docker-compose and docker-compose-1.17.1.

So, it couldn't work.

**Comment by andrewrothstein** [comment]
the download creates /usr/local/bin/docker-compose-X.Y.Z and then creates a link to it at /usr/local/bin/docker-compose. If you have a file at /usr/local/bin/docker-compose it won't work. Delete /usr/local/bin/docker-compose on all of your target machines and reapply the role.
